"""Report generation.

A report is built once as a list of content blocks and then rendered twice
over: to a real Word document (.docx) when python-docx is installed, and to
Word-flavoured HTML (.doc) otherwise, which Word, LibreOffice and Google Docs
all open. One content model, two encodings, so the two can never drift.

Every report carries the tier it was produced under, the officer who produced
it, and a SHA-256 digest of its content. The digest is taken over the content
model rather than over either encoding, so the same report digests identically
in both formats, and it is written to the audit ledger at export time: a
printed report can be checked against the ledger entry that recorded it.
"""
from __future__ import annotations

import hashlib
import html
import json
import time
from typing import Any, Iterable

from . import config

try:  # A real .docx is preferable; the HTML fallback keeps the demo running.
    import docx  # noqa: F401
    from docx import Document
    from docx.enum.section import WD_ORIENT  # noqa: F401
    from docx.enum.table import WD_TABLE_ALIGNMENT
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    from docx.oxml import OxmlElement
    from docx.oxml.ns import qn
    from docx.shared import Cm, Pt, RGBColor
    DOCX_AVAILABLE = True
except ImportError:  # pragma: no cover - exercised only on a bare install
    DOCX_AVAILABLE = False


# --------------------------------------------------------------------------
# Content model
#
# Every block is a tuple whose first element names its kind:
#   ("masthead", title, subtitle)
#   ("h2" | "h3", text)
#   ("p" | "stmt" | "notice" | "limit", text)
#   ("kv", [(key, value, style|None), ...])
#   ("table", [headers], [[cells], ...], [highlighted row indexes])
#   ("digest", hex)
# `style` is "mono" or None. Nothing in the model is markup.
# --------------------------------------------------------------------------

Block = tuple


def _txt(v: Any) -> str:
    return "" if v is None else str(v)


def _inr(n: Any) -> str:
    try:
        return "Rs " + f"{int(round(float(n))):,}"
    except (TypeError, ValueError):
        return _txt(n)


def _score(v: Any) -> str:
    if v is None:
        return "—"
    try:
        return f"{float(v):.2f}"
    except (TypeError, ValueError):
        return _txt(v)


def _params(d: dict[str, Any] | None) -> str:
    return "; ".join(f"{k.replace('_', ' ')} = {v}" for k, v in (d or {}).items())


def _digest(blocks: list[Block]) -> str:
    payload = json.dumps(blocks, ensure_ascii=False, sort_keys=True, default=str)
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


# --------------------------------------------------------------------------
# Sections
# --------------------------------------------------------------------------

def _provenance(principal, report_id: str,
                extra: Iterable[tuple[str, Any]] = ()) -> Block:
    rows = [
        ("Report reference", report_id, "mono"),
        ("Generated", time.strftime("%d %B %Y, %H:%M"), None),
        ("Generated by", f"{principal.display} — {principal.unit}", None),
        ("Access tier applied", ", ".join(principal.tiers), None),
        ("Classification", "Prototype / synthetic data", None),
    ]
    rows.extend((k, _txt(v), None) for k, v in extra)
    return ("kv", rows)


NOTICE = ("notice",
          "Data notice. This report is produced from synthetic demonstration "
          "data. It does not describe any real person, case, account, vehicle "
          "or telephone number. Findings are analytical products and are not "
          "evidence in themselves; each states the limitations under which it "
          "was produced.")


def _finding_blocks(f: dict[str, Any], number: str | None = None) -> list[Block]:
    head = f"{number}. {f['finding_type']}" if number else f["finding_type"]
    out: list[Block] = [("h2", head), ("stmt", f["statement"])]

    out.append(("kv", [
        ("Finding reference", f["finding_id"], "mono"),
        ("Mechanism family", config.MECHANISM_FAMILIES.get(
            f.get("mechanism_family", ""), f.get("mechanism_family", "")), None),
        ("Mechanism", f["mechanism"], "mono"),
        ("Mechanism version", _txt(f.get("model_version")), "mono"),
        ("Parameters used", _params(f.get("mechanism_params")), "mono"),
        ("Confidence", f"{f['confidence']:.3f}", None),
        ("Confidence means", _txt(f.get("confidence_meaning")), None),
        ("Access tier", _txt(f.get("tier", "standard")), None),
        ("Status", _txt(f.get("status", "pending")).upper(), None),
    ]))

    ev = f.get("evidence") or []
    if ev:
        out.append(("h3", f"Evidence ({len(ev)} record{'' if len(ev) == 1 else 's'})"))
        out.append(("table",
                    ["Record", "Type", "Role in the finding", "Source record"],
                    [[_txt(e.get("node_id")), _txt(e.get("label")),
                      _txt(e.get("role")), _txt(e.get("source_record_id"))] for e in ev],
                    []))

    merges = f.get("contributing_merges") or []
    if merges:
        out.append(("h3", "Entity resolution decisions behind this finding"))
        out.append(("p", "If one of these merges is incorrect, this finding is "
                         "incorrect. Each is reversible."))
        out.append(("table", ["Merge reference"], [[_txt(m)] for m in merges], []))

    out.extend(_mechanism_blocks(f))

    out.append(("h3", "Known limitations"))
    out.append(("limit", _txt(f.get("limitations"))))

    out.append(("h3", "Investigator decision"))
    if f.get("status") != "pending":
        out.append(("kv", [
            ("Decision", _txt(f.get("status")).upper(), None),
            ("Decided by", _txt(f.get("decided_by")), None),
            ("Decided at", _txt(f.get("decided_at")).replace("T", " "), None),
            ("Reason recorded", _txt(f.get("decision_reason")), None),
        ]))
    else:
        out.append(("p", "Not yet reviewed. This finding is pending human "
                         "confirmation and must not be acted on as a conclusion."))
    return out


def _mechanism_blocks(f: dict[str, Any]) -> list[Block]:
    """The per-mechanism working, so the report stands on its own off-screen."""
    x = f.get("extra") or {}
    m = f.get("mechanism")

    if m == "rule.structuring" and x.get("deposits"):
        rows = [[_txt(d.get("from")), _inr(d.get("amount")),
                 _txt(d.get("when")).replace("T", " ")[:16], _txt(d.get("channel"))]
                for d in x["deposits"]]
        rows.append(["Total", _inr(x.get("total")),
                     f"over {_txt(x.get('window_hours'))} hours", ""])
        return [("h3", "Deposits that satisfied the rule"),
                ("table", ["From", "Amount", "When", "Channel"], rows,
                 list(range(len(x["deposits"]))))]

    if m == "statistical.benford" and x.get("suspect"):
        s, c = x["suspect"], x.get("control") or {}
        rows = [[str(i + 1), _txt(o), _txt(s["expected"][i])]
                for i, o in enumerate(s.get("observed", []))]
        return [
            ("h3", "First-digit distribution"),
            ("table", ["Leading digit", "Observed", "Benford expected"], rows, []),
            ("kv", [
                ("Sample size (n)", _txt(s.get("n")), None),
                ("Orders of magnitude", _txt(s.get("orders_of_magnitude")), None),
                ("Mean absolute deviation", _txt(s.get("mad")), None),
                ("Chi-square", f"{s.get('chi2')} (critical "
                               f"{s.get('critical_value_chi2_p01')} at p=0.01)", None),
                ("Verdict", _txt(s.get("verdict")), None),
                ("Control group", f"{_txt(c.get('verdict', 'n/a'))} (n={c.get('n', 0)})", None),
            ])]

    if m == "timeseries.cusum" and x.get("series"):
        return [("h3", "Change-point detection"), ("kv", [
            ("Baseline mean daily credit", _inr(x.get("mu0")), None),
            ("Mean after change point", _inr(x.get("post_change_mean")), None),
            ("Change detected on", _txt(x.get("alarm_date")), None),
            ("Decision limit (h)", _txt(x.get("h")), None),
            ("Days observed", str(len(x.get("series", []))), None),
        ])]

    if m == "vector.mo_similarity" and x.get("narratives"):
        out = [("h3", "Comparison"), ("kv", [
            ("Structured feature similarity", _txt(x.get("feature_similarity")), None),
            ("Narrative text similarity", _txt(x.get("text_similarity")), None),
            ("Combined score", _txt(x.get("combined")), None),
            ("Shared entities", ", ".join(x.get("shared_entities") or []) or "none", None),
        ]), ("table", ["Case", "Narrative as filed"],
             [[k, v] for k, v in x["narratives"].items()], [])]
        if x.get("agreeing_features"):
            out.append(("table", ["Attribute", "Value in both cases"],
                        [[_txt(k), _txt(v)] for k, v in x["agreeing_features"].items()], []))
        return out

    if m == "structural.community_bridge":
        if x.get("top_by_betweenness"):
            ri = x.get("removal_impact") or {}
            subjects = set(f.get("subject_ids") or [])
            rows, hi = [], []
            for i, r in enumerate(x["top_by_betweenness"]):
                rows.append([_txt(r.get("display")), _txt(r.get("label")),
                             _txt(r.get("betweenness"))])
                if r.get("id") in subjects:
                    hi.append(i)
            return [("h3", "Betweenness ranking in the bounded subgraph"),
                    ("table", ["Record", "Type", "Betweenness"], rows, hi),
                    ("kv", [
                        ("Communities detected", _txt(x.get("n_communities")), None),
                        ("Communities spanned", _txt(x.get("communities_spanned")), None),
                        ("Components before removal", _txt(ri.get("components_before")), None),
                        ("Components after removal", _txt(ri.get("components_after"))
                         + (" — removal splits the network" if ri.get("splits") else ""), None),
                    ])]
        if x.get("path"):
            rows = [[str(i + 1), _txt(n.get("display")), _txt(n.get("label"))]
                    for i, n in enumerate(x["path"].get("nodes", []))]
            return [("h3", "Traced path"),
                    ("table", ["#", "Record", "Type"], rows, list(range(len(rows))))]

    if f.get("mechanism_family") == "er" and (x.get("merge") or x.get("merges")):
        out: list[Block] = []
        for mg in [g for g in (x.get("merges") or [x.get("merge")]) if g and g.get("fields")]:
            rows = [[_txt(fl.get("field")), _score(fl.get("score")),
                     "deterministic" if fl.get("weight") is None else _txt(fl.get("weight")),
                     _txt(fl.get("note"))] for fl in mg["fields"]]
            th = mg.get("thresholds") or {}
            out.extend([
                ("h3", f"Field agreement — {mg.get('left_display')} vs {mg.get('right_display')}"),
                ("table", ["Field", "Score", "Weight", "Note"], rows, []),
                ("kv", [
                    ("Method", _txt(mg.get("method")), None),
                    ("Overall score", _txt(mg.get("score")), None),
                    ("Decision", _txt(mg.get("decision")), None),
                    ("Thresholds", f"review at {th.get('tau_low')}, "
                                   f"auto-merge at {th.get('tau_high')}", None),
                ]),
                ("limit", _txt(mg.get("rationale"))),
            ])
        return out
    return []


def _network_blocks(ego: dict[str, Any], case_id: str) -> list[Block]:
    by_label: dict[str, int] = {}
    for n in ego.get("nodes", []):
        by_label[n["label"]] = by_label.get(n["label"], 0) + 1
    by_type: dict[str, int] = {}
    for e in ego.get("edges", []):
        by_type[e["type"]] = by_type.get(e["type"], 0) + 1

    return [
        ("h2", "2. Network extracted around this case"),
        ("kv", [
            ("Centred on", case_id, "mono"),
            ("Traversal depth", f"{ego.get('hops', 2)} hops", None),
            ("Records returned", str(len(ego.get("nodes", []))), None),
            ("Relationships returned", str(len(ego.get("edges", []))), None),
            ("Bound applied", f"{ego.get('cap')} nodes"
             + (" (reached)" if ego.get("truncated") else " (not reached)"), None),
        ]),
        ("h3", "Composition"),
        ("table", ["Record type", "Count"],
         [[k, str(v)] for k, v in sorted(by_label.items(), key=lambda kv: -kv[1])], []),
        ("h3", "Relationships"),
        ("table", ["Relationship", "Count"],
         [[k, str(v)] for k, v in sorted(by_type.items(), key=lambda kv: -kv[1])], []),
        ("h3", "Records in the extracted network"),
        ("table", ["Reference", "Type", "Identifier", "Source record"],
         [[n["id"], n["label"], n["display"], n["source_record_id"]]
          for n in sorted(ego.get("nodes", []), key=lambda n: (n["label"], n["id"]))], []),
    ]


# --------------------------------------------------------------------------
# Public builders — each returns (blocks, report_id)
# --------------------------------------------------------------------------

def case_report(case: dict[str, Any], ego: dict[str, Any],
                findings: list[dict[str, Any]], principal,
                hidden_count: int = 0) -> tuple[list[Block], str]:
    """Full case file: particulars, extracted network, every relevant finding."""
    props = case.get("props", {})
    case_id = case["id"]
    report_id = f"CNAS/RPT/{case_id}/{time.strftime('%Y%m%d-%H%M%S')}"

    blocks: list[Block] = [
        ("masthead", "Case Analysis Report",
         f"{props.get('title', case_id)} ({case_id})"),
        _provenance(principal, report_id),
        NOTICE,
        ("h2", "1. Case particulars"),
        ("kv", [
            ("Case reference", case_id, "mono"),
            ("Title", _txt(props.get("title")), None),
            ("Crime category", _txt(props.get("crime")), None),
            ("District", _txt(props.get("district")), None),
            ("Date opened", _txt(props.get("opened")), None),
            ("Investigating officer", _txt(props.get("officer")), None),
            ("Source record", _txt(case.get("source_record_id")), "mono"),
            ("Access tier of record", _txt(case.get("tier", "standard")), None),
        ]),
    ]
    blocks.extend(_network_blocks(ego, case_id))

    blocks.append(("h2", f"3. Findings on this network ({len(findings)})"))
    if not findings:
        blocks.append(("p", "No detection mechanism returned a finding on this "
                            "network at the access tier applied."))
    else:
        blocks.append(("table", ["Reference", "Finding", "Confidence", "Status"],
                       [[f["finding_id"], f["finding_type"], f"{f['confidence']:.2f}",
                         _txt(f.get("status")).upper()] for f in findings], []))
        for i, f in enumerate(findings, start=1):
            blocks.extend(_finding_blocks(f, number=f"3.{i}"))

    if hidden_count:
        blocks.append(("h2", "4. Withheld at this access tier"))
        blocks.append(("p", f"{hidden_count} record(s) in the system are outside "
                            "the access tier under which this report was produced "
                            "and are neither counted nor described above."))
    return blocks, report_id


def finding_report(f: dict[str, Any], principal) -> tuple[list[Block], str]:
    """One finding, with its complete explainability record."""
    report_id = f"CNAS/RPT/{f['finding_id']}/{time.strftime('%Y%m%d-%H%M%S')}"
    blocks: list[Block] = [
        ("masthead", "Finding Report", f["finding_type"]),
        _provenance(principal, report_id),
        NOTICE,
    ]
    blocks.extend(_finding_blocks(f))
    return blocks, report_id


def queue_report(findings: list[dict[str, Any]], principal,
                 scope: str = "All findings") -> tuple[list[Block], str]:
    """The review queue as filed: summary table, then each record in full."""
    report_id = f"CNAS/RPT/QUEUE/{time.strftime('%Y%m%d-%H%M%S')}"
    counts = {"pending": 0, "confirmed": 0, "rejected": 0}
    for f in findings:
        st = f.get("status", "pending")
        counts[st] = counts.get(st, 0) + 1

    blocks: list[Block] = [
        ("masthead", "Review Queue Report", scope),
        _provenance(principal, report_id, extra=[
            ("Findings in report", len(findings)),
            ("Pending / confirmed / rejected",
             f"{counts['pending']} / {counts['confirmed']} / {counts['rejected']}"),
        ]),
        NOTICE,
        ("h2", "1. Summary"),
        ("table", ["Reference", "Mechanism family", "Finding", "Confidence", "Status"],
         [[f["finding_id"],
           config.MECHANISM_FAMILIES.get(f.get("mechanism_family", ""), ""),
           f["finding_type"], f"{f['confidence']:.2f}",
           _txt(f.get("status")).upper()] for f in findings], []),
        ("h2", "2. Findings in full"),
    ]
    for i, f in enumerate(findings, start=1):
        blocks.extend(_finding_blocks(f, number=f"2.{i}"))
    return blocks, report_id


# --------------------------------------------------------------------------
# Renderer: Word (.docx)
# --------------------------------------------------------------------------

NAVY = (0x1B, 0x3A, 0x5F)
GREY = (0x44, 0x44, 0x44)
AMBER_BG = "FDF6E6"
HEAD_BG = "E8EAED"
KEY_BG = "F4F5F7"
HI_BG = "EAF0F8"


def _shade(cell, hex_fill: str) -> None:
    el = OxmlElement("w:shd")
    el.set(qn("w:val"), "clear")
    el.set(qn("w:fill"), hex_fill)
    cell._tc.get_or_add_tcPr().append(el)


def _rule(paragraph, size: int = 12, color: str = "1B3A5F") -> None:
    """A horizontal rule, which Word expresses as a bottom paragraph border."""
    pbdr = OxmlElement("w:pBdr")
    bottom = OxmlElement("w:bottom")
    bottom.set(qn("w:val"), "single")
    bottom.set(qn("w:sz"), str(size))
    bottom.set(qn("w:space"), "3")
    bottom.set(qn("w:color"), color)
    pbdr.append(bottom)
    paragraph._p.get_or_add_pPr().append(pbdr)


def _run(p, text: str, *, bold=False, size=10.5, color=None, mono=False, caps=False):
    r = p.add_run(text.upper() if caps else text)
    r.bold = bold
    r.font.size = Pt(size)
    r.font.name = "Consolas" if mono else "Calibri"
    if color:
        r.font.color.rgb = RGBColor(*color)
    return r


def _box(doc, text: str, fill: str, bar_color: str | None = None):
    """A callout, which Word does most reliably as a one-cell shaded table."""
    t = doc.add_table(rows=1, cols=1)
    t.style = "Table Grid"
    t.alignment = WD_TABLE_ALIGNMENT.LEFT
    cell = t.cell(0, 0)
    _shade(cell, fill)
    p = cell.paragraphs[0]
    _run(p, text, size=9.5)
    doc.add_paragraph()
    return t


def render_docx(blocks: list[Block], digest: str, path_or_stream) -> None:
    doc = Document()

    sec = doc.sections[0]
    sec.page_height, sec.page_width = Cm(29.7), Cm(21.0)
    sec.top_margin = sec.bottom_margin = Cm(2.0)
    sec.left_margin = sec.right_margin = Cm(1.8)

    normal = doc.styles["Normal"]
    normal.font.name = "Calibri"
    normal.font.size = Pt(10.5)

    for block in blocks:
        kind = block[0]

        if kind == "masthead":
            p = doc.add_paragraph()
            _run(p, "Criminal Network Analysis System", bold=True, size=9,
                 color=NAVY, caps=True)
            p = doc.add_paragraph()
            _run(p, block[1], bold=True, size=18)
            p = doc.add_paragraph()
            _run(p, block[2], size=11, color=GREY)
            _rule(p)

        elif kind == "h2":
            p = doc.add_paragraph()
            p.paragraph_format.space_before = Pt(14)
            _run(p, block[1], bold=True, size=13, color=NAVY)
            _rule(p, size=6, color="9AA0A6")

        elif kind == "h3":
            p = doc.add_paragraph()
            p.paragraph_format.space_before = Pt(10)
            _run(p, block[1], bold=True, size=11)

        elif kind == "p":
            _run(doc.add_paragraph(), block[1])

        elif kind == "stmt":
            p = doc.add_paragraph()
            _run(p, block[1], size=11.5)

        elif kind == "notice":
            _box(doc, block[1], KEY_BG)

        elif kind == "limit":
            _box(doc, block[1], AMBER_BG)

        elif kind == "kv":
            rows = block[1]
            t = doc.add_table(rows=len(rows), cols=2)
            t.style = "Table Grid"
            for i, (k, v, style) in enumerate(rows):
                kc, vc = t.cell(i, 0), t.cell(i, 1)
                kc.width, vc.width = Cm(5.2), Cm(12.0)
                _shade(kc, KEY_BG)
                _run(kc.paragraphs[0], _txt(k), size=9.5, bold=True)
                _run(vc.paragraphs[0], _txt(v), size=9.5, mono=(style == "mono"))
            doc.add_paragraph()

        elif kind == "table":
            headers, rows, hi = block[1], block[2], set(block[3] or [])
            t = doc.add_table(rows=len(rows) + 1, cols=len(headers))
            t.style = "Table Grid"
            for j, h in enumerate(headers):
                cell = t.cell(0, j)
                _shade(cell, HEAD_BG)
                _run(cell.paragraphs[0], h, bold=True, size=9, caps=True)
            for i, row in enumerate(rows, start=1):
                for j, val in enumerate(row):
                    cell = t.cell(i, j)
                    if (i - 1) in hi:
                        _shade(cell, HI_BG)
                    _run(cell.paragraphs[0], _txt(val), size=9)
            doc.add_paragraph()

    p = doc.add_paragraph()
    _rule(p, size=6, color="9AA0A6")
    p = doc.add_paragraph()
    _run(p, "Document digest (SHA-256): ", size=8.5, color=GREY)
    _run(p, digest, size=8.5, mono=True, color=GREY)
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.LEFT
    _run(p, "This digest is recorded in the CNAS audit ledger at the moment of "
            "export. A report whose digest is absent from the ledger was not "
            "produced by this system.", size=8.5, color=GREY)

    doc.save(path_or_stream)


# --------------------------------------------------------------------------
# Renderer: Word-flavoured HTML (.doc), used when python-docx is not installed
# --------------------------------------------------------------------------

_STYLE = """
@page { size: A4; margin: 2.0cm 1.8cm; }
body { font-family: Calibri, Arial, sans-serif; font-size: 10.5pt; color: #111;
       line-height: 1.42; }
h1 { font-size: 18pt; margin: 0 0 2pt; }
h2 { font-size: 13pt; color: #1b3a5f; margin: 18pt 0 6pt;
     border-bottom: .75pt solid #9aa0a6; padding-bottom: 3pt; }
h3 { font-size: 11pt; margin: 12pt 0 4pt; }
p { margin: 0 0 6pt; }
table { border-collapse: collapse; width: 100%; margin: 4pt 0 10pt; font-size: 9pt; }
th { background: #e8eaed; border: .75pt solid #9aa0a6; padding: 4pt 6pt;
     text-align: left; font-size: 9pt; text-transform: uppercase; }
td { border: .75pt solid #9aa0a6; padding: 4pt 6pt; vertical-align: top; }
td.k { background: #f4f5f7; width: 28%; font-weight: bold; }
tr.hi td { background: #eaf0f8; }
.mono { font-family: Consolas, "Courier New", monospace; }
.org { font-size: 9pt; letter-spacing: 1.4pt; text-transform: uppercase;
       color: #1b3a5f; font-weight: bold; }
.sub { font-size: 11pt; color: #444; border-bottom: 2.25pt solid #1b3a5f;
       padding-bottom: 8pt; margin-bottom: 6pt; }
.stmt { font-size: 11.5pt; margin: 4pt 0 8pt; }
.box { border: .75pt solid #9aa0a6; background: #f4f5f7; padding: 6pt 8pt;
       font-size: 9.5pt; margin: 8pt 0; }
.box.warn { background: #fdf6e6; border-left: 3pt solid #8a5a00; }
.foot { border-top: .75pt solid #9aa0a6; margin-top: 16pt; padding-top: 6pt;
        font-size: 8.5pt; color: #444; }
"""

_HEAD = """<html xmlns:o="urn:schemas-microsoft-com:office:office"
      xmlns:w="urn:schemas-microsoft-com:office:word"
      xmlns="http://www.w3.org/TR/REC-html40">
<head><meta charset="utf-8">
<meta name="ProgId" content="Word.Document">
<title>{title}</title>
<!--[if gte mso 9]><xml><w:WordDocument><w:View>Print</w:View>
</w:WordDocument></xml><![endif]-->
<style>{style}</style></head><body>
"""


def _e(v: Any) -> str:
    return html.escape(_txt(v), quote=False)


def render_html(blocks: list[Block], digest: str, title: str) -> str:
    out: list[str] = []
    for block in blocks:
        kind = block[0]
        if kind == "masthead":
            out.append(f"<div class='org'>Criminal Network Analysis System</div>"
                       f"<h1>{_e(block[1])}</h1>"
                       f"<div class='sub'>{_e(block[2])}</div>")
        elif kind in ("h2", "h3"):
            out.append(f"<{kind}>{_e(block[1])}</{kind}>")
        elif kind == "p":
            out.append(f"<p>{_e(block[1])}</p>")
        elif kind == "stmt":
            out.append(f"<p class='stmt'>{_e(block[1])}</p>")
        elif kind == "notice":
            out.append(f"<div class='box'>{_e(block[1])}</div>")
        elif kind == "limit":
            out.append(f"<div class='box warn'>{_e(block[1])}</div>")
        elif kind == "kv":
            rows = "".join(
                f"<tr><td class='k'>{_e(k)}</td>"
                f"<td{' class=mono' if style == 'mono' else ''}>{_e(v)}</td></tr>"
                for k, v, style in block[1])
            out.append(f"<table>{rows}</table>")
        elif kind == "table":
            headers, rows, hi = block[1], block[2], set(block[3] or [])
            head = "".join(f"<th>{_e(h)}</th>" for h in headers)
            body = "".join(
                f"<tr{' class=hi' if i in hi else ''}>"
                + "".join(f"<td>{_e(c)}</td>" for c in row) + "</tr>"
                for i, row in enumerate(rows))
            out.append(f"<table><tr>{head}</tr>{body}</table>")

    foot = (f"<div class='foot'>Document digest (SHA-256): "
            f"<span class='mono'>{digest}</span><br>"
            "This digest is recorded in the CNAS audit ledger at the moment of "
            "export. A report whose digest is absent from the ledger was not "
            "produced by this system.</div>")
    return _HEAD.format(title=_e(title), style=_STYLE) + "".join(out) + foot + "</body></html>"


# --------------------------------------------------------------------------
# Encoding entry point
# --------------------------------------------------------------------------

DOCX_MEDIA_TYPE = ("application/vnd.openxmlformats-officedocument."
                   "wordprocessingml.document")


def render(blocks: list[Block], basename: str,
           fmt: str = "docx") -> tuple[bytes, str, str, str]:
    """Return (payload, filename, media type, digest) for the requested format."""
    digest = _digest(blocks)
    if fmt == "docx" and DOCX_AVAILABLE:
        import io
        buf = io.BytesIO()
        render_docx(blocks, digest, buf)
        return buf.getvalue(), f"{basename}.docx", DOCX_MEDIA_TYPE, digest
    document = render_html(blocks, digest, basename.replace("-", " "))
    return (document.encode("utf-8"), f"{basename}.doc",
            "application/msword", digest)
